spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 3000
      login-timeout: 5

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.mysqldemo.entity.po
  configuration:
    # 取消驼峰下划线转换
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: uuid
      # 第二种方法，在配置文件里设置update时的字段策略，这里选择ignored，即忽略检测null字段，即可进行全字段更新
#      update-strategy: ignored